var path=require('path');
var webpack=require('webpack');
module.exports={
    context:path.resolve(__dirname,'src'),
    entry:{
        app:'./index.js'
    },
    output:{
        path:path.resolve(__dirname,'dist','assets'),
        filename:'bundle.js',
        publicPath:'/assets'
    },
    watch:true,
    devServer:{
        contentBase:path.resolve(__dirname,'public')
    },
    module:{
        rules:[
            {
                test:/\.js$/i,
                exclude:[/node_modules/],
                use:[
                    {
                        loader:'babel-loader',
                        options:{presets:['env']}
                    }
                ]
            },
            {
                test:/\.css$/i,
                use:['style-loader','css-loader']
            },
            {
                test:/\.(scss|sass)$/i,
                use:['style-loader','css-loader','sass-loader']
            }
        ]
    },
    resolve:{
        modules:[path.resolve(__dirname,'src'),'node_modules']
    }
}