var path=require('path');
var webpack=require('webpack');
var ExtractTextPlugin=require('extract-text-webpack-plugin');
module.exports={
    context:path.resolve(__dirname,'src'),
    entry:{
        app:'./index.js'
    },
    output:{
        path:path.resolve(__dirname,'dist','assets'),
        filename:'bundle.js',
        publicPath:'/assets'
    },
    watch:true,
    devServer:{
        contentBase:path.resolve(__dirname,'public')
    },
    module:{
        rules:[
            {
                test:/\.js$/i,
                exclude:[/node_modules/],
                use:[
                    {
                        loader:'babel-loader',
                        options:{presets:['env']}
                    }
                ]
            },
            {
                test:/\.(sass|scss|css)$/i,
                use:[
                    {
                        loader:ExtractTextPlugin.extract(['style-loader','css-loader','sass-loader'])
                    }
                ]
            }
        ]
    },
    plugins:[
        new ExtractTextPlugin({
            filename:"assets/[name].css",
            allChunks:true
        })
    ],
    resolve:{
        modules:[path.resolve(__dirname,'src'),'node_modules']
    }
}